const portfolio = [
  ['semanal','Festival da Carne','#d9242b','#70181e'],['semanal','Semana do Hortifruti','#4c9b5b','#1e5936'],['varejo','Economia Todo Dia','#f09c30','#c64227'],['semanal','Ofertas de Fim de Semana','#5b2d91','#251344'],['varejo','Clube de Vantagens','#1e5fa8','#18385d'],['sazonal','Black Friday','#1d1d20','#a32424'],['semanal','Especial Churrasco','#e14a20','#76200f'],['varejo','Volta às Aulas','#d64f84','#712048'],['sazonal','Natal de Preços Baixos','#136343','#0b2e28'],['varejo','Aniversário da Loja','#ecb231','#a53725'],['semanal','Quarta da Economia','#6259a7','#2f2a5d'],['sazonal','Páscoa Especial','#7a5437','#3b2419']
];
const grid=document.querySelector('#portfolio-grid');
function showPortfolio(filter='all'){grid.innerHTML='';portfolio.forEach(([category,title,c1,c2])=>{if(filter!=='all'&&filter!==category)return;const item=document.createElement('button');item.className='portfolio-item';item.dataset.title=title;item.dataset.category='campanha completa';item.dataset.color=`linear-gradient(145deg,${c1},${c2})`;item.innerHTML=`<div class="portfolio-art" style="--c1:${c1};--c2:${c2}"><small>ENCARTE · FEED · STORIES · WHATSAPP · BANNER</small><strong>${title}</strong></div>`;grid.appendChild(item)})}showPortfolio();
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('[data-filter].active').classList.remove('active');button.classList.add('active');showPortfolio(button.dataset.filter)}));
const modal=document.querySelector('#portfolio-modal');grid.addEventListener('click',e=>{const item=e.target.closest('.portfolio-item');if(!item)return;document.querySelector('#modal-art').style.background=item.dataset.color;document.querySelector('#modal-category').textContent=item.dataset.category;document.querySelector('#modal-title').textContent=item.dataset.title;modal.classList.add('open');modal.setAttribute('aria-hidden','false')});document.querySelector('.modal-close').onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};modal.addEventListener('click',e=>{if(e.target===modal)document.querySelector('.modal-close').click()});
const slider=document.querySelector('#compare-slider'),before=document.querySelector('#compare-before'),handle=document.querySelector('#compare-handle');slider.addEventListener('input',()=>{before.style.width=`${slider.value}%`;handle.style.left=`${slider.value}%`});
const header=document.querySelector('#header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20));
document.querySelector('#menu-button').onclick=()=>document.querySelector('#mobile-menu').classList.toggle('hidden');document.querySelectorAll('#mobile-menu a').forEach(a=>a.onclick=()=>document.querySelector('#mobile-menu').classList.add('hidden'));
const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');addEventListener('mousemove',e=>{dot.style.left=ring.style.left=`${e.clientX}px`;dot.style.top=ring.style.top=`${e.clientY}px`});
document.querySelector('#year').textContent=new Date().getFullYear();window.addEventListener('load',()=>{AOS.init({once:true,offset:55,duration:650});setTimeout(()=>document.querySelector('#loader').classList.add('done'),400)});
